PSBT and HSM refactor
Coldcard/firmware pull request #142
Opened 2022-08-29 18:45 UTC by straylight-orbit

This PR is mainly a refactor along with some improvements. The changes are as follows:

1. OP_RETURN outputs that spend (burn) 0 sats are no longer subjected to whitelist testing. This is because they're harmless and don't consume value.

2. OP_RETURN tests used to require a running bitcoind instance. This is no longer the case because `fake_txn` has been updated to support arbitrary OP_RETURN data.

3. PSBT proxy objects were caching the `amount` value in `validate`. This wasn't the best place because that method is concerned with validating own outputs. This has been moved to `consider_outputs`. Scriptpubkey is now also cached there.

4. As a consequence of caching scriptpubkey in proxy objects, the expensive `output_iter` method which operates directly on the filesystem no longer needs to be called when doing whitelist checks. This should result in improved performance. There are probably other places that could benefit from a similar refactor.

5. Whitelist checks have been moved to a more appropriate place (`rule.matches_transaction`).

All tests have been run against the simulator and no regressions have been introduced.

2022-08-30 07:24 UTC, scgbckbone commented
1. not sure about this - once user specify a whitelist - does he really wants to sign transaction with random number of OP_RETURN scripts ? "harmless" is understatement as you still have to pay fees for them
2. lgtm (yet I would still test with bitcoind so the fake_txn isn't the only OP_RETURN provider against which we test)
3.,4.,5. ok

2022-08-30 07:26 UTC, scgbckbone reviewed
1. not sure about this - once user specify a whitelist - does he really wants to sign transaction with random number of OP_RETURN scripts ? "harmless" is understatement as you still have to pay fees for them
2. lgtm (yet I would still test with bitcoind so the fake_txn isn't the only OP_RETURN provider against which we test)
3.,4.,5. ok

2022-08-31 12:44 UTC, scgbckbone commented
in our test suite, for some tests fresh simulator is needed (one of them is `test_sign.py::test_bip143_attack_data_capture[True-100]`)

As we expect some tests to fail during the run - we have implemented our own test driver that replays failed test after each run against fresh simulator ---> check module doc string in `testing/run_sim_tests.py` (firmware).

2022-08-31 12:53 UTC, scgbckbone commented
Second thoughts - you're right with harmlessness (based on my knowledge). But IMO once you have a whitelist, it should only allow what is whitelisted - by definition.

If you want/need to allow random OP_RETURN scripts ?maybe? some new  policy option (default=do not allow random OP_RETURN) and not part of whitelist...

2022-08-31 12:54 UTC, scgbckbone requested changes
above

2022-08-31 17:52 UTC, scgbckbone approved these changes
Tested ACK

2022-09-02 11:10 UTC, scgbckbone commented
You also need an ACK from @doc-hex to get this in. Just build on top of this - rebasing is easy...

2022-09-02 12:01 UTC, doc-hex commented on testing/txn.py
> +    from binascii import hexlify
please use `b2a_hex` rather than poorly named `hexlify`

2022-09-02 12:09 UTC, doc-hex commented
Looking good, safe to build on... just need to satisfy my pet-peeve about `b2a_hex`

2022-09-02 18:26 UTC, merged