HSM Dynamic Whitelisting
Coldcard/firmware pull request #143
Opened 2022-09-03 17:14 UTC by straylight-orbit

This PR introduces a new HSM mode that enables dynamic whitelisting.

### Why is this needed?

While the Coldcard can tell which outputs belong to itself, blocking malicious outputs in HSM mode is difficult. This is normally solved with whitelisting. But whitelisting works only with static addresses and is not practical in dynamic applications where destination addresses are unknown ahead of time. Sometimes we want "dynamic" whitelisting where a PSBT can prove to the Coldcard that foreign outputs are legitimate.

### How is this achieved?

Outputs can be attested by trusted keys, where a trusted key creates a signature (attestation) over a serialized txout and thereby says "I am OK with this scriptpubkey and its amount". Each foreign output's attestation is attached to a custom per-output proprietary PSBT entry (proprietary keys format is defined in [BIP174](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki#proprietary-use-type)).

Public keys (addresses) used for verification are loaded into the HSM policy using the existing `whitelist` list.

### Usage
HSM policy example that uses attestation-based dynamic whitelisting:

```json
{
    "rules": [
        {
            "whitelist": [
                "17eet2ZwDT4PHvsYeTiWggMQUYfRfA3XYH",
                "1BQdJXHXao72kMWmDBppvEkR56EXxWSrnN"
            ],
            "whitelist_opts": {
                "mode": "ATTEST",
                "allow_zeroval_outs": true
            }
        }
    ]
}
```

`whitelist_opts` is a new structure that contains two fields:
- `mode: str`: `BASIC` or `ATTEST`. `BASIC` is the old behavior where whitelisting is based on address comparison. `ATTEST` is the new attestation mode.
- `allow_zeroval_outs: bool`: whether to always allow outputs with no value (OP_RETURN) without requiring attestation. This setting applies to either mode.

An output that has been attested will set the following key-value pair in its own PSBT entry.

- key:
-- keytype: ` 0xFC` -- stands for `proptietary`, defined by BIP174
-- identifier: `COINKITE` (global namespace used by Coldcard)
-- subtype: `0` (we define this as "attestation signature")
-- keydata: empty
- value:
-- 65 byte recoverable signature

### Verification process

A Coldcard with a policy designed to perform attestation-based whitelisting takes the following steps:

1. extracts attached attestation (signature) for each PSBT output entry
2. if output is foreign, its signature is verified and a public key is recovered from it
3. extracted public key is hashed, converted to an address and checked against addresses in the whitelist
4. if present in the whitelist pass, otherwise fail

### Testing

Existing tests are passing and no regressions have been introduced. New tests have been written that test the attestation mode by covering txouts with both valid and invalid signatures and assert the correct outcome. PSBT serialization/deserialization when attestation values are present has also been covered. Legacy OP_RETURN whitelist tests have been updated to take `allow_zeroval_outs` into account.

@doc-hex @scgbckbone

2022-09-04 08:11 UTC, scgbckbone requested changes
conceptACK (I like it very much as it is making whitelisting sooo much more flexible)

* no guessing of address type --> use header byte to decide addr format

2022-09-04 08:11 UTC, scgbckbone commented on shared/psbt.py
> +PSBT_OUT_PROPRIETARY = const(0xFC)
why is this OUT? isn't proprietary in global namespace?

2022-09-04 08:11 UTC, scgbckbone commented on shared/auth.py
> +def verify_recover_message_digest(sig, digest):
`verify_recover_pubkey` ?? --> maybe this method could also return address format (AF_<what>) based on parsed header byte?

2022-09-04 09:29 UTC, scgbckbone commented
| y-parity | x-order | recovery id | v | addr type | addr prefix |
|:--------:|:-----------:|:-----------:|:--:|:----------------------:|:------------------:|
| 0 | less than n | 0 | 27 | uncompressed p2pkh | 1, m, n |
| 1 | less than n | 1 | 28 | uncompressed p2pkh | 1, m, n |
| 0 | more than n | 2 | 29 | uncompressed p2pkh | 1, m, n |
| 1 | more than n | 3 | 30 | uncompressed p2pkh | 1, m, n |
| 0 | less than n | 0 | 31 | compressed p2pkh | 1, m, n |
| 1 | less than n | 1 | 32 | compressed p2pkh | 1, m, n |
| 0 | more than n | 2 | 33 | compressed p2pkh | 1, m, n |
| 1 | more than n | 3 | 34 | compressed p2pkh | 1, m, n |
| 0 | less than n | 0 | 35 | compressed p2sh-p2wpkh | 3, 2 |
| 1 | less than n | 1 | 36 | compressed p2sh-p2wpkh | 3, 2 |
| 0 | more than n | 2 | 37 | compressed p2sh-p2wpkh | 3, 2 |
| 1 | more than n | 3 | 38 | compressed p2sh-p2wpkh | 3, 2 |
| 0 | less than n | 0 | 39 | compressed p2wpkh | bc1q, tb1q, bcrt1q |
| 1 | less than n | 1 | 40 | compressed p2wpkh | bc1q, tb1q, bcrt1q |
| 0 | more than n | 2 | 41 | compressed p2wpkh | bc1q, tb1q, bcrt1q |
| 1 | more than n | 3 | 42 | compressed p2wpkh | bc1q, tb1q, bcrt1q |
| does NOT | support | recovery | 46 | compressed p2tr | bc1p |


`v` in table is a header byte - this is the table which I created as a response to https://github.com/ZenulAbidin/bips/blob/master/bip-notatether-signedmessage.mediawiki which has some typo/bugs there - this is how I think author intended to specify it so we do not fork BIP137

2022-09-05 09:22 UTC, scgbckbone approved these changes
this attestation mode is lit! I was thinking about something similar, but I wanted to go down the way of xpubs and derivation - however this is much better - thank you! now let's get @doc-hex on board

2022-09-05 09:22 UTC, scgbckbone commented on testing/helpers.py
> +        # Python doesn't support byte assignment so make a list first...
I'd prefer it this way (sorry for cosmetic comments):
`bytes([sig[0] + adjust]) + sig[1:]`

2022-09-05 09:22 UTC, scgbckbone commented on shared/psbt.py
> -def read_varint(v):
why deleted? unused ?

2022-09-05 14:23 UTC, doc-hex commented
I also feel this is "lit". Will review and merge.

2022-09-09 10:42 UTC, scgbckbone commented
please squash the commits

2022-09-09 12:08 UTC, scgbckbone commented
Could you also add short but descriptive sentence to `releases/ChangeLog-mk4.md`?

2022-09-09 12:08 UTC, scgbckbone approved these changes

2022-09-10 09:10 UTC, scgbckbone requested changes

2022-09-10 09:10 UTC, scgbckbone commented on releases/ChangeLog-mk4.md
> +- Enhancement: Dynamic whitelisting in HSM mode is now possible. Foreign outputs can
Enhancement: HSM dynamic whitelisting. Foreign outputs can be attested by being signed with a private key corresponding to the address specified in `whitelist` section. Attestation signature MUST be provided in PSBT.

?

2022-09-10 11:06 UTC, scgbckbone approved these changes
Thanks

2022-09-15 18:26 UTC, merged